{
 "title": "Beholder Insurance",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Organization Count",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "organizations_created_count_total"
    }
   ]
  },
  {
   "title": "Quotation count",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "quotation_count_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Distributed Tracing",
   "type": "traces",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 0 },
   "targets": [
    { "service": "jaeger-all-in-one" }
   ]
  },
  {
   "title": "my logs",
   "type": "logs",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"Yosef\"} |= ``"
    }
   ]
  }
 ]
}